# Generated by Django 4.2.7 on 2024-06-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='ai_category',
            field=models.ManyToManyField(blank=True, to='partners.aicategory'),
        ),
        migrations.AddField(
            model_name='partners',
            name='case_study',
            field=models.ManyToManyField(blank=True, to='partners.casestudy'),
        ),
        migrations.AddField(
            model_name='partners',
            name='product_info',
            field=models.ManyToManyField(blank=True, to='partners.productinfo'),
        ),
        migrations.AddField(
            model_name='partners',
            name='service_content',
            field=models.ManyToManyField(blank=True, to='partners.servicecontent'),
        ),
        migrations.RemoveField(
            model_name='partners',
            name='cost',
        ),
        migrations.AddField(
            model_name='partners',
            name='cost',
            field=models.ManyToManyField(blank=True, to='partners.cost'),
        ),
    ]
