# Generated by Django 4.2.7 on 2024-06-11 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_partners_ai_category_partners_case_study_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partners',
            old_name='enginner',
            new_name='engineer',
        ),
    ]
